# MEDIACLI ENVIRONMENT - Auto-generated by Vault Agent
# DO NOT EDIT - Changes will be overwritten

{{- with secret "secret/mediacli/env" }}
PUID={{ .Data.data.PUID }}
PGID={{ .Data.data.PGID }}
UMASK={{ .Data.data.UMASK }}
TZ={{ .Data.data.TZ }}
HOSTNAME={{ .Data.data.HOSTNAME }}
CONFIG_BASE_PATH={{ .Data.data.CONFIG_BASE_PATH }}
DATA_PATH={{ .Data.data.DATA_PATH }}
{{- end }}

# API KEYS
{{- with secret "secret/mediacli/sonarr" }}
SONARR_API_KEY={{ .Data.data.api_key }}
{{- end }}

{{- with secret "secret/mediacli/radarr" }}
RADARR_API_KEY={{ .Data.data.api_key }}
{{- end }}

{{- with secret "secret/mediacli/prowlarr" }}
PROWLARR_API_KEY={{ .Data.data.api_key }}
{{- end }}

{{- with secret "secret/mediacli/bazarr" }}
BAZARR_API_KEY={{ .Data.data.api_key }}
{{- end }}

{{- with secret "secret/mediacli/jellyseerr" }}
JELLYSEERR_API_KEY={{ .Data.data.api_key }}
{{- end }}

{{- with secret "secret/mediacli/qbittorrent" }}
QBITTORRENT_USER={{ .Data.data.username }}
QBITTORRENT_PASS={{ .Data.data.password }}
{{- end }}
