services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    hostname: bazarr.${HOSTNAME}
    logging:
      driver: json-file
    ports:
      - 6767:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_BASE_PATH}/bazarr:/config
      - ${DATA_PATH}:/data
    restart: always