services:
  emby:
    container_name: embyserver
    image: emby/embyserver
    hostname: emby.${HOSTNAME}
    logging:
      driver: json-file
    ports:
      - 8096:8096
      - 8920:8920
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_BASE_PATH}/emby:/config
      - ${DATA_PATH}:/data
    restart: always