services:  
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    hostname: prowlarr.${HOSTNAME}
    logging:
      driver: json-file
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_BASE_PATH}/prowlarr:/config
    restart: always