services:  
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    hostname: qbit.${HOSTNAME}
    logging:
      driver: json-file
    ports:
      - 6681:6681/tcp
      - 6681:6881/udp
      - 8080:8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_BASE_PATH}/qbittorrent:/config
      - ${DATA_PATH}:/data
    restart: always