services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    hostname: radarr.${HOSTNAME}
    logging:
      driver: json-file
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_BASE_PATH}/radarr:/config
      - ${DATA_PATH}:/data
    restart: always