services:
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    hostname: recyclarr.${HOSTNAME}
    logging:
      driver: json-file
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_BASE_PATH}/recyclarr:/config
    restart: on-failure