services: 
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    hostname: sonarr.${HOSTNAME}
    logging:
      driver: json-file
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_BASE_PATH}/sonarr:/config
      - ${DATA_PATH}:/data
    restart: always